version: '3.1'

services:

  mongo:
    image: mongo
    container_name: graphqlDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker

